// This file is generated by Slice Machine. Update with care!

import Post from './Post';
import Posts from './Posts';

export {
	Post,
	Posts,
};

export const components = {
	post: Post,
	posts: Posts,
};
